language: node_js

node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=test

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = test ]; then
      npm run site
      php -S localhost:8000 &
      CI=true npm run test
    fi
