language: node_js

node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=unit
    - TEST_TYPE=e2e-src
    - TEST_TYPE=e2e-dist

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = uitest ]; then
      npm run unit
    elif [ "$TEST_TYPE" = e2e-src ]; then
      npm run e2e
    elif [ "$TEST_TYPE" = e2e-dist ]; then
      npm run site
      mv dist/* ./
      php -S localhost:8000 &
      npm test -- '\.e2e\.js'
    fi
